### ISSUE TITLE
Merge in vasculature to tissue/organ mappings to VCCF

### ISSUE THREAD

**Issue by dosumis** [obophenotype/vccf-ontology#1]
Vasculature → tissue/organ mappings https://github.com/hubmapconsortium/hra-vccf/blob/main/VesselOrganCrosswalk.csv

**Comment by anitacaron** [comment]
Robot template created and imported in VCCF https://github.com/obophenotype/vccf-ontology/blob/main/src/templates/vessel_organ_crosswalk.tsv

**Comment by dosumis** [comment]
Do we have supporting references for these?

**Comment by anitacaron** [comment]
It seems not.
